package projecteuler.problems;

import projecteuler.util.ComplexMath;

public class P12 implements Problem{
    public P12() {
        super();
    }
    
    public void execute() {
        System.out.println("The sequence of triangle numbers is generated by adding the natural numbers.\n" + 
        "So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:\n" + 
        "\n" + 
        "1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...\n" + 
        "\n" + 
        "Let us list the factors of the first seven triangle numbers:\n" + 
        "\n" + 
        " 1: 1\n" + 
        " 3: 1,3\n" + 
        " 6: 1,2,3,6\n" + 
        "10: 1,2,5,10\n" + 
        "15: 1,3,5,15\n" + 
        "21: 1,3,7,21\n" + 
        "28: 1,2,4,7,14,28\n" + 
        "\n" + 
        "We can see that 28 is the first triangle number to have over five divisors.\n" + 
        "\n" + 
        "What is the value of the first triangle number to have over five hundred divisors?");
        
        final int NUM_DIVISORS = 500;
        long triangle_number = 0;
        boolean complete = false;
        
        for (int i = 1; complete == false; i++) {
            triangle_number += i;
            int total_divisors; 
            if (i % 2 == 0) {
                total_divisors = ComplexMath.getNumDivisors(i/2) * ComplexMath.getNumDivisors(i+1);
            }
            else {
                total_divisors = ComplexMath.getNumDivisors(i) * ComplexMath.getNumDivisors((i + 1) / 2);
            }
            if (total_divisors > NUM_DIVISORS) {
                complete = true;
            }
            System.out.println(triangle_number + " has " + total_divisors);
        }
        
        System.out.println("\nAnswer: " + triangle_number);
    }
}