package projecteuler.problems;

import java.math.BigInteger;
import java.util.TreeSet;


public class P29 implements Problem {
    public P29() {
        super();
    }

    @Override
    public void execute() {
        System.out.println("Consider all integer combinations of a^b for 2 ? a ? 5 and 2 ? b ? 5:\n" + 
        "\n" + 
        "2^2=4, 2^3=8, 2^4=16, 2^5=32\n" + 
        "3^2=9, 3^3=27, 3^4=81, 3^5=243\n" + 
        "4^2=16, 4^3=64, 4^4=256, 4^5=1024\n" + 
        "5^2=25, 5^3=125, 5^4=625, 5^5=3125\n" + 
        "If they are then placed in numerical order, with any repeats removed, we get the following sequence of 15 distinct terms:\n" + 
        "\n" + 
        "4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125\n" + 
        "\n" + 
        "How many distinct terms are in the sequence generated by ab for 2 <= a <= 100 and 2 <= b <= 100?");
        
        TreeSet<BigInteger> nums = new TreeSet<BigInteger>();
        
        for (int i = 2; i <= 100; i++) {
            for (int j = 2; j <= 100; j++) {
                nums.add(BigInteger.valueOf(i).pow(j));
            }
        }
        
        System.out.println("\nAnswer:" + nums.size());
    }
}
