package projecteuler.problems;

import java.util.*;

public class P45 implements Problem {
    public P45() {
        super();
    }
    
    @Override
    public void execute() {
        System.out.println("Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:\n" + 
        "\n" + 
        "Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...\n" + 
        "Pentagonal	 	Pn=n(3n?1)/2	 	1, 5, 12, 22, 35, ...\n" + 
        "Hexagonal	 	Hn=n(2n?1)	 	1, 6, 15, 28, 45, ...\n" + 
        "It can be verified that T285 = P165 = H143 = 40755.\n" + 
        "\n" + 
        "Find the next triangle number that is also pentagonal and hexagonal.");
        
        long result = 0L;
        
        for (int i = 144; result == 0L; i++) {
            long hexag = (long) (2 * Math.pow(i, 2) - i);
            if ((1 + Math.sqrt(1 + 24 * hexag)) % 6 == 0) result = hexag;
        }
        
        System.out.println("\nAnswer: " + result);
    }
}